### ISSUE TITLE
TypeError: 'generator' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by JakSla** [maxpumperla/hyperas#136]
This is just for reference if someone comes across it as well to not waste his time.
It's another name for TypeError: 'generator' object is not subscriptable.
issue was resolved by simply installing networkx in older version as in other case.
do
pip install networkx==1.11

Traceback (most recent call last):
  File "bayesian_optimization.py", line 90, in <module>
    trials=Trials())
  File "/usr/local/lib/python2.7/dist-packages/hyperas/optim.py", line 67, in minimize
    verbose=verbose)
  File "/usr/local/lib/python2.7/dist-packages/hyperas/optim.py", line 133, in base_minimizer
    return_argmin=True),
  File "/usr/local/lib/python2.7/dist-packages/hyperopt/fmin.py", line 307, in fmin
    return_argmin=return_argmin,
  File "/usr/local/lib/python2.7/dist-packages/hyperopt/base.py", line 635, in fmin
    return_argmin=return_argmin)
  File "/usr/local/lib/python2.7/dist-packages/hyperopt/fmin.py", line 314, in fmin
    pass_expr_memo_ctrl=pass_expr_memo_ctrl)
  File "/usr/local/lib/python2.7/dist-packages/hyperopt/base.py", line 786, in __init__
    pyll.toposort(self.expr)
  File "/usr/local/lib/python2.7/dist-packages/hyperopt/pyll/base.py", line 715, in toposort
    assert order[-1] == expr
TypeError: 'generator' object has no attribute '__getitem__'

seems like exactly the same issue, but different error message.

**Comment by abrad1212** [comment]
@JakSla did you manage to fix this?

**Comment by JakSla** [comment]
as per issue comment i provided:
"
It's another name for TypeError: 'generator' object is not subscriptable.
issue was resolved by simply installing networkx in older version as in
other case.
do
pip install networkx==1.11 It's another name for TypeError: 'generator'
object is not subscriptable.
issue was resolved by simply installing networkx in older version as in
other case.
do
pip install networkx==1.11
"

2018-04-04 23:26 GMT+02:00 abrad1212 <notifications@github.com>:
