### ISSUE TITLE
TypeError: 'function' object is not subscriptable

### ISSUE THREAD

**Issue by gaceladri** [maxpumperla/hyperas#147]
Hi guys,

Really good job. I am having the next issue and I already installed networkx==1.11 but the issue persist.

`Traceback (most recent call last):
  File "lshhyperas.py", line 135, in <module>
    trials=Trials())
  File "/home/proto/anaconda3/envs/tensorflow/lib/python3.5/site-packages/hyperas/optim.py", line 67, in minimize
    verbose=verbose)
  File "/home/proto/anaconda3/envs/tensorflow/lib/python3.5/site-packages/hyperas/optim.py", line 128, in base_minimizer
    space=get_space(),
  File "/home/proto/Downloads/initialnet/training_/temp_model.py", line 223, in get_space
TypeError: 'function' object is not subscriptable`

Any suggestion about what is about?
Thanks!

**Comment by BenMacKenzie** [comment]
my problem was i had {{choice[1,2,3]}}

should have been {{choice([1,2,3])}}

**Comment by maxpumperla** [comment]
@gaceladri sorry for now coming back earlier.

yeah @BenMacKenzie is right, this is just improper usage most likely. this is usually indicative of missing `()`  around a function like `choice`, but I can't tell for sure unless you show me your code. (btw, this is perfectly googleable, returns a million SO answers)

It'd be really great to start from hyperas examples and compare what you're doing to what's going on there.
