### ISSUE TITLE
Usage with multiple inputs and custom layers

### ISSUE THREAD

**Issue by pabucur** [maxpumperla/hyperas#159]
Is it possible to use hyperas in the presence of models with multiple input and custom layers?

In my case, I get an exception that the custom layer is not known:

```
Traceback (most recent call last):
  File "C:/Users/bucpau/PycharmProjects/Acoustics/Models/CanonicalCorrelationAnalysis/DCCA/DCCA_hyperparam.py", line 305, in <module>
    main()
  File "C:/Users/bucpau/PycharmProjects/Acoustics/Models/CanonicalCorrelationAnalysis/DCCA/DCCA_hyperparam.py", line 283, in main
    trials=Trials())
  File "C:\ProgramData\Anaconda3\lib\site-packages\hyperas-0.4-py3.6.egg\hyperas\optim.py", line 67, in minimize
    verbose=verbose)
  File "C:\ProgramData\Anaconda3\lib\site-packages\hyperas-0.4-py3.6.egg\hyperas\optim.py", line 136, in base_minimizer
    return_argmin=True),
  File "C:\ProgramData\Anaconda3\lib\site-packages\hyperopt\fmin.py", line 307, in fmin
    return_argmin=return_argmin,
  File "C:\ProgramData\Anaconda3\lib\site-packages\hyperopt\base.py", line 635, in fmin
    return_argmin=return_argmin)
  File "C:\ProgramData\Anaconda3\lib\site-packages\hyperopt\fmin.py", line 320, in fmin
    rval.exhaust()
  File "C:\ProgramData\Anaconda3\lib\site-packages\hyperopt\fmin.py", line 199, in exhaust
    self.run(self.max_evals - n_done, block_until_done=self.async)
  File "C:\ProgramData\Anaconda3\lib\site-packages\hyperopt\fmin.py", line 173, in run
    self.serial_evaluate()
  File "C:\ProgramData\Anaconda3\lib\site-packages\hyperopt\fmin.py", line 92, in serial_evaluate
    result = self.domain.evaluate(spec, ctrl)
  File "C:\ProgramData\Anaconda3\lib\site-packages\hyperopt\base.py", line 840, in evaluate
    rval = self.fn(pyll_rval)
  File "C:\Users\bucpau\PycharmProjects\Acoustics\Models\CanonicalCorrelationAnalysis\DCCA\temp_model.py", line 179, in keras_fmin_fnct
NameError: name 'CCA' is not defined

```

**Comment by maxpumperla** [comment]
@pabucur not sure how your setup is / where you define CCA, but note that you can provide custom functions like this to hyperas:

https://github.com/maxpumperla/hyperas/blob/master/examples/use_intermediate_functions.py

not sure if this helps. let me know! (feel free to show some code)

**Comment by pabucur** [comment]
@maxpumperla what I have are two input sources, from which the inputs are passed through two neural networks respectively, concatenated and fed into the final CCA layer. The model looks like:

```
def create_model(x_train, y_train, x_test, y_test):


    batch_size = {{uniform(100, 3000)}}
    batch_size = int(batch_size)
    n_epochs = {{uniform(5, 20)}}
    n_epochs = int(n_epochs)

    representation_size = 50
    timesteps = 2600

    input_a = Input(shape=(timesteps,))
    dense1_1 = GaussianNoise({{uniform(0.05, 5)}})(input_a)
    dense1_1 = BatchNormalization()(dense1_1)
    dense1_1 = Dense({{choice([3, 6, 10, 12, 24, 50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 1500, 2000, 3000])}}, activation={{choice(['relu', 'selu', 'tanh', 'sigmoid'])}})(dense1_1)
    dense1_1 = Dropout({{uniform(0, 1)}})(dense1_1)
    dense1_1 = Dense({{choice([3, 6, 10, 12, 24, 50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 1500, 2000, 3000])}}, activation={{choice(['relu', 'selu', 'tanh', 'sigmoid'])}})(dense1_1)
    dense1_1 = Dropout({{uniform(0, 1)}})(dense1_1)
    dense1_1 = Dense({{choice([3, 6, 10, 12, 24, 50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 1500, 2000, 3000])}}, activation={{choice(['relu', 'selu', 'tanh', 'sigmoid'])}})(dense1_1)
    dense1_1 = Dropout({{uniform(0, 1)}})(dense1_1)
    dense1_1 = Dense({{choice([3, 6, 10, 12, 24, 50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 1500, 2000, 3000])}}, activation={{choice(['relu', 'selu', 'tanh', 'sigmoid'])}})(dense1_1)
    dense1_1 = Dropout({{uniform(0, 1)}})(dense1_1)
    dense1_1 = Dense({{choice([3, 6, 10, 12, 24, 50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 1500, 2000, 3000])}}, activation={{choice(['relu', 'selu', 'tanh', 'sigmoid'])}})(dense1_1)
    dense1_1 = Dropout({{uniform(0, 1)}})(dense1_1)
    view_a = Dense(representation_size, activation='relu')(dense1_1)

    input_b = Input(shape=(timesteps,))
    dense1_2 = GaussianNoise({{uniform(0.05, 5)}})(input_b)
    dense1_2 = BatchNormalization()(dense1_2)
    dense1_2 = Dense({{choice([3, 6, 10, 12, 24, 50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 1500, 2000, 3000])}}, activation={{choice(['relu', 'selu', 'tanh', 'sigmoid'])}})(dense1_2)
    dense1_2 = Dropout({{uniform(0, 1)}})(dense1_2)
    dense1_2 = Dense({{choice([3, 6, 10, 12, 24, 50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 1500, 2000, 3000])}}, activation={{choice(['relu', 'selu', 'tanh', 'sigmoid'])}})(dense1_2)
    dense1_2 = Dropout({{uniform(0, 1)}})(dense1_2)
    dense1_2 = Dense({{choice([3, 6, 10, 12, 24, 50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 1500, 2000, 3000])}}, activation={{choice(['relu', 'selu', 'tanh', 'sigmoid'])}})(dense1_2)
    dense1_2 = Dropout({{uniform(0, 1)}})(dense1_2)
    dense1_2 = Dense({{choice([3, 6, 10, 12, 24, 50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 1500, 2000, 3000])}}, activation={{choice(['relu', 'selu', 'tanh', 'sigmoid'])}})(dense1_2)
    dense1_2 = Dropout({{uniform(0, 1)}})(dense1_2)
    dense1_2 = Dense({{choice([3, 6, 10, 12, 24, 50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 1500, 2000, 3000])}}, activation={{choice(['relu', 'selu', 'tanh', 'sigmoid'])}})(dense1_2)
    dense1_2 = Dropout({{uniform(0, 1)}})(dense1_2)
    view_b = Dense(50, activation='relu')(dense1_2)

    shared_layer = concatenate([view_a, view_b], name='shared_layer')
    custom_cca_layer = CCA(k_singular_values=representation_size, representation_size=representation_size, batch_size=batch_size)(shared_layer)
    merged_model = Model(inputs=[input_a, input_b], outputs=custom_cca_layer)
    merged_model.compile(loss=dummy_loss_correlation, optimizer=RMSprop(lr=0.0001))
    merged_model.summary()

    x_train_, x_val, y_train_, y_val = train_test_split(x_train, y_train, test_size=0.2, shuffle=True)

    # Labels all set to zero since they are not used in the cross-decomposition model
    print('Beginning training')
    merged_model.fit(x=[x_train_, y_train_], y=np.zeros(len(x_train_)), batch_size=batch_size, epochs=n_epochs, shuffle=True, verbose=1)

    score, acc = merged_model.evaluate(([x_val, y_val], np.zeros(len(x_val))), verbose=0)
    print('Validation correlation: {}'.format(score))

    return {'loss': score, 'model': merged_model}
```
with CCA defined as:

```
class CCA(Layer):

    def __init__(self, k_singular_values=50, representation_size=50, batch_size=37, **kwargs):
        self.representation_size = representation_size
        self.k_singular_values = k_singular_values
        self.batch_size = batch_size
        super(CCA, self).__init__(**kwargs)

    def build(self, input_shape):
        # Create a trainable weight variable for this layer.
        super(CCA, self).build(input_shape)

    def call(self, y_pred):

        regularization_constant_1 = tf.constant([1e-4])
        regularization_constant_2 = tf.constant([1e-4])
        epsilon = tf.constant([1e-12])

        o1 = o2 = tf.shape(y_pred)[1] // 2
        h_1 = y_pred[:, 0:o1]
        h_2 = y_pred[:, o1:o1 + o2]

        # h_1 and h_2 are R^(o,m) matrices in the paper
        h_1 = tf.transpose(h_1)
        h_2 = tf.transpose(h_2)

        m = tf.shape(h_1)[1]

        one_matrix = tf.ones([m, m])

        one = tf.constant([1.0], dtype=tf.float32)
        m = tf.cast(m, dtype=tf.float32)

        centered_h_1 = h_1 - tf.divide(one, m) * tf.matmul(h_1, one_matrix)
        centered_h_2 = h_2 - tf.divide(one, m) * tf.matmul(h_2, one_matrix)

        sigma_hat_12 = tf.divide(one, m - 1) * tf.matmul(centered_h_1, tf.transpose(centered_h_2))

        sigma_hat_11 = tf.divide(one, m - 1) * tf.matmul(centered_h_1, tf.transpose(centered_h_1)) + regularization_constant_1 * tf.eye(num_rows=o1)

        sigma_hat_22 = tf.divide(one, m - 1) * tf.matmul(centered_h_2, tf.transpose(centered_h_2)) + regularization_constant_2 * tf.eye(num_rows=o2)

        [w_1, v_1] = tf.py_func(my_eigen, [sigma_hat_11], [tf.float32, tf.float32])
        [w_2, v_2] = tf.py_func(my_eigen, [sigma_hat_22], [tf.float32, tf.float32])

        idx_pos_entries_1 = tf.where(w_1 > epsilon)
        idx_pos_entries_1 = tf.squeeze(idx_pos_entries_1)

        w_1 = tf.gather(w_1, idx_pos_entries_1)
        v_1 = tf.gather(v_1, idx_pos_entries_1)

        idx_pos_entries_2 = tf.where(w_2 > epsilon)
        idx_pos_entries_2 = tf.squeeze(idx_pos_entries_2)

        w_2 = tf.gather(w_2, idx_pos_entries_2)
        v_2 = tf.gather(v_2, idx_pos_entries_2)

        pow_value = tf.constant([-0.5])
        mult_1 = tf.matmul(v_1, tf.diag(tf.pow(w_1, pow_value)))
        sigma_hat_rootinvert_11 = tf.matmul(mult_1, tf.transpose(v_1))
        mult_2 = tf.matmul(v_2, tf.diag(tf.pow(w_2, pow_value)))
        sigma_hat_rootinvert_22 = tf.matmul(mult_2, tf.transpose(v_2))

        t_matrix = tf.matmul(tf.matmul(sigma_hat_rootinvert_11, sigma_hat_12), sigma_hat_rootinvert_22)

        if self.k_singular_values == self.representation_size:  # use all
            correlation = tf.trace(T.sqrt(tf.matmul(tf.transpose(t_matrix), t_matrix)))
            """
            [U,D,V]=svd(T,0);
            U=U(:,1:K);
            D=D(1:K,1:K);
            V=V(:,1:K);
            corr=sum(sum(D));
            """
            #s = tf.svd(t_matrix, compute_uv=False)
            #correlation = tf.reduce_sum(s)
        else:
            w, v = tf.self_adjoint_eig(K.dot(K.transpose(t_matrix), t_matrix))
            non_critical_indexes = tf.where(tf.equal(tf.greater(w, epsilon), True))
            non_critical_indexes = tf.reshape(non_critical_indexes, [-1, tf.shape(non_critical_indexes)[0]])[0]
            w = tf.gather(w, non_critical_indexes)
            w = tf.gather(w, tf.nn.top_k(w[:, 2]).indices)
            correlation = T.sum(T.sqrt(w[0:self.representation_size]))

        return tf.convert_to_tensor(-correlation)
```

**Comment by maxpumperla** [comment]
thanks for your feedback, forgot to close.
