### ISSUE TITLE
TypeError: 'generator' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by bboynton97** [maxpumperla/hyperas#169]
I'm running into this error when following the tutorial on my own dataset

```
>>> Resulting replaced keras model:

   1: def keras_fmin_fnct(space):
   2: 
   3:     model = Sequential()
   4:     model.add(Dense(space['Dense'],input_dim=hm_col))
   5:     model.add(Activation('relu'))
   6:     model.add(Dropout(space['Dropout']))
   7:     model.add(Dense(space['Dense_1']))
   8:     model.add(Activation(space['Activation']))
   9:     model.add(Dropout(space['Dropout_1']))
  10:     
  11:     if conditional(space['conditional']) == 'four':
  12:         model.add(Dense(100))
  13: 
  14:         # We can also choose between complete sets of layers
  15: 
  16:         model.add(space['add'])
  17:         model.add(Activation('relu'))
  18:         
  19:     model.add(Dense(10))
  20:     model.add(Activation('linear'))
  21: 
  22:     model.compile(loss='mean_absolute_error', metrics=['mae'],
  23:                   optimizer=space['optimizer'])
  24: 
  25:     model.fit(x_train, y_train,
  26:               batch_size=space['batch_size'],
  27:               epochs=15,
  28:               verbose=2,
  29:               validation_data=(x_test, y_test))
  30:     
  31:     mean_error = mean_absolute_error(y_true, y_scores)
  32:     print('Test error:', mean_error)
  33:     return {'loss': mean_error, 'status': STATUS_OK, 'model': model}
  34: 
Traceback (most recent call last):
  File "hpo.py", line 171, in <module>
    trials=Trials())
  File "/usr/local/lib/python2.7/dist-packages/hyperas/optim.py", line 67, in minimize
    verbose=verbose)
  File "/usr/local/lib/python2.7/dist-packages/hyperas/optim.py", line 133, in base_minimizer
    return_argmin=True),
  File "/usr/local/lib/python2.7/dist-packages/hyperopt/fmin.py", line 307, in fmin
    return_argmin=return_argmin,
  File "/usr/local/lib/python2.7/dist-packages/hyperopt/base.py", line 635, in fmin
    return_argmin=return_argmin)
  File "/usr/local/lib/python2.7/dist-packages/hyperopt/fmin.py", line 314, in fmin
    pass_expr_memo_ctrl=pass_expr_memo_ctrl)
  File "/usr/local/lib/python2.7/dist-packages/hyperopt/base.py", line 786, in __init__
    pyll.toposort(self.expr)
  File "/usr/local/lib/python2.7/dist-packages/hyperopt/pyll/base.py", line 715, in toposort
    assert order[-1] == expr
```

**Comment by bboynton97** [comment]
Solution here: https://github.com/hyperopt/hyperopt/issues/357
