### ISSUE TITLE
Is Python 3 supported?

### ISSUE THREAD

**Issue by nikicc** [maxpumperla/hyperas#20]
I got the following error when installing in Python 3.4, hence the question: do you support Python 3? If not yet, are there any plans to do it in the near future? I see that you currently run test only for 2.7.

```
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "/Users/<NAME>/Projects/virtual_envs/testing123/build/hyperopt/setup.py", line 119, in <module>
    if package_data is None: package_data = find_package_data(packages)
  File "/Users/<NAME>/Projects/virtual_envs/testing123/build/hyperopt/setup.py", line 102, in find_package_data
    for subdir in find_subdirectories(package):
  File "/Users/Niko/Projects/virtual_envs/testing123/build/hyperopt/setup.py", line 73, in find_subdirectories
    subdirectories = os.walk(package_to_path(package)).next()[1]
AttributeError: 'generator' object has no attribute 'next'
```

**Comment by maxpumperla** [comment]
Thanks, that's because hyperopt doesn't support python 3, which is a pity. Nothing I can do about it right now.

**Comment by hadim** [comment]
hyperopt seems to be working with Python 3, at least the installation. See https://github.com/hyperopt/hyperopt/issues/255

When running the hyperas example I have the following error but I can't tell if its because of hyperas or hyperopt ?

```
Unexpected error: <class 'SyntaxError'>
  File "/home/hadim/Insync/Documents/Code/notebooks/Private-Notebooks/Deep Learning/temp_model.py", line 1
    importers when locating support scripts as well as when importing modules.
                 ^
SyntaxError: invalid syntax
```

Any help would be appreciated.
