### ISSUE TITLE
Graph Disconnected Error

### ISSUE THREAD

**Issue by MdAsifKhan** [maxpumperla/hyperas#21]
Hi, I am using hyperas to optimize my model. There seems to be some issue it works fine for few epochs after that it gives following error:
Traceback (most recent call last):
  File "parameter_tuning.py", line 240, in <module>
    main(*sys.argv)
  File "parameter_tuning.py", line 180, in main
    best_run, best_model = optim.minimize(model=model,data=load_data, algo=tpe.suggest, max_evals=10, trials= Trials())
  File "/usr/local/lib/python2.7/dist-packages/hyperas/optim.py", line 31, in minimize
    best_run = base_minimizer(model, data, algo, max_evals, trials, rseed)
  File "/usr/local/lib/python2.7/dist-packages/hyperas/optim.py", line 111, in base_minimizer
    rseed=rseed)
  File "/usr/local/lib/python2.7/dist-packages/hyperopt/fmin.py", line 334, in fmin
    rval.exhaust()
  File "/usr/local/lib/python2.7/dist-packages/hyperopt/fmin.py", line 294, in exhaust
    self.run(self.max_evals - n_done, block_until_done=self.async)
  File "/usr/local/lib/python2.7/dist-packages/hyperopt/fmin.py", line 268, in run
    self.serial_evaluate()
  File "/usr/local/lib/python2.7/dist-packages/hyperopt/fmin.py", line 187, in serial_evaluate
    result = self.domain.evaluate(spec, ctrl)
  File "/usr/local/lib/python2.7/dist-packages/hyperopt/fmin.py", line 114, in evaluate
    rval = self.fn(pyll_rval)
  File "/home/khanma0b/keras-master/deepgo-master/temp_model.py", line 121, in keras_fmin_fnct
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 1683, in **init**
    str(layers_with_complete_input))
Exception: Graph disconnected: cannot obtain value for tensor input_1 at layer "input_1". The following previous layers were accessed without issue: []

**Comment by maxpumperla** [comment]
sorry I didn't follow up on this. we have made a lot of changes since then. I will close this for now, feel free to re-open if problems persist. thanks
