### ISSUE TITLE
import error with bson

### ISSUE THREAD

**Issue by MrWanter** [maxpumperla/hyperas#23]
After I installed hyperas using'pip install hyperas', I run the example code of lstm, but it raise an error: 'ImportError: No module named bson', I then pip to intall bson, 'pip install bson', but it raise an error:
' Command "python setup.py egg_info" failed with error code 1 in c:\users\admi
ni~1\appdata\local\temp\pip-build-jx55yy\bson', can someone help me, thanks in advance.

**Comment by maxpumperla** [comment]
Hi, hyperopt seems to have problems with bson module. You could try to uninstall bson and then do ```pip install pymongo```, which comes with its own version of bson.

**Comment by MrWanter** [comment]
Thank you! After I uninstalled bson and installed pymongo, the previous error have been solved, but a new one came up, the following is the error information:
`Unexpected error: <type 'exceptions.NameError'>
Traceback (most recent call last):

  File "<ipython-input-2-5352e829afa4>", line 1, in <module>
    runfile('C:/SciSoft/my_code/untitled0.py', wdir='C:/SciSoft/my_code')

  File "C:\SciSoft\WinPython-64bit-2.7.9.4\python-2.7.9.amd64\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 682, in runfile
    execfile(filename, namespace)

  File "C:\SciSoft\WinPython-64bit-2.7.9.4\python-2.7.9.amd64\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 71, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "C:/SciSoft/my_code/untitled0.py", line 78, in <module>
    trials=Trials())

  File "C:\SciSoft\WinPython-64bit-2.7.9.4\python-2.7.9.amd64\lib\site-packages\hyperas\optim.py", line 31, in minimize
    best_run = base_minimizer(model, data, algo, max_evals, trials, rseed)

  File "C:\SciSoft\WinPython-64bit-2.7.9.4\python-2.7.9.amd64\lib\site-packages\hyperas\optim.py", line 96, in base_minimizer
    from temp_model import keras_fmin_fnct, get_space

  File "temp_model.py", line 8, in <module>
    spy_cfg.IPKernelApp.pylab_import_all = autoload_pylab_o

NameError: name 'autoload_pylab_o' is not defined`
BTW, I have a well established envirorment for keras and theano.

**Comment by MrWanter** [comment]
Please, help me, I'm really puzzeled.
