### ISSUE TITLE
How to use keras clear_session() with hyperas?

### ISSUE THREAD

**Issue by TimZaragori** [maxpumperla/hyperas#259]
Hello everyone, I am trying to use hyperas to tune the hyperparameters of my model. 

Problem is I must use `keras.backend.tensorflow_backend.clear_session()` after each model fitted to clear GPU memory. If I don't I am getting an error when loading the model after a few iterations (I am getting the same error when I try to loop on models outside hyperas).

When I use `clear_session()` either at the beginning or at the end of `create_model()` I have the following error, before fitting the model if at the beginning or after fitting if placed at the end : 
`Traceback (most recent call last):
  File "opti_mnistrot.py", line 841, in <module>
    bayesian_optimization()
  File "opti_mnistrot.py", line 800, in bayesian_optimization
    max_evals=50, trials=Trials(), rseed=111, functions=functions, keep_temp=True)
  File "C:\Users\stage_clinique\AppData\Local\Continuum\anaconda3\envs\tf_gpu1.14\lib\site-packages\hyperas\optim.py", line 69, in minimize
    keep_temp=keep_temp)
  File "C:\Users\stage_clinique\AppData\Local\Continuum\anaconda3\envs\tf_gpu1.14\lib\site-packages\hyperas\optim.py", line 139, in base_minimizer
    return_argmin=True),
  File "C:\Users\stage_clinique\AppData\Local\Continuum\anaconda3\envs\tf_gpu1.14\lib\site-packages\hyperopt\fmin.py", line 403, in fmin
    show_progressbar=show_progressbar,
  File "C:\Users\stage_clinique\AppData\Local\Continuum\anaconda3\envs\tf_gpu1.14\lib\site-packages\hyperopt\base.py", line 651, in fmin
    show_progressbar=show_progressbar)
  File "C:\Users\stage_clinique\AppData\Local\Continuum\anaconda3\envs\tf_gpu1.14\lib\site-packages\hyperopt\fmin.py", line 422, in fmin
    rval.exhaust()
  File "C:\Users\stage_clinique\AppData\Local\Continuum\anaconda3\envs\tf_gpu1.14\lib\site-packages\hyperopt\fmin.py", line 276, in exhaust
    self.run(self.max_evals - n_done, block_until_done=self.asynchronous)
  File "C:\Users\stage_clinique\AppData\Local\Continuum\anaconda3\envs\tf_gpu1.14\lib\site-packages\hyperopt\fmin.py", line 241, in run
    self.serial_evaluate()
  File "C:\Users\stage_clinique\AppData\Local\Continuum\anaconda3\envs\tf_gpu1.14\lib\site-packages\hyperopt\fmin.py", line 141, in serial_evaluate
    result = self.domain.evaluate(spec, ctrl)
  File "C:\Users\stage_clinique\AppData\Local\Continuum\anaconda3\envs\tf_gpu1.14\lib\site-packages\hyperopt\base.py", line 856, in evaluate
    rval = self.fn(pyll_rval)
  File "C:\Users\stage_clinique\Desktop\DOPA\Code_Python\DonutConv\DonutConv_TF1\temp_model.py", line 767, in keras_fmin_fnct
    callbacks=[lrate_function], verbose=1)
  File "C:\Users\stage_clinique\AppData\Local\Continuum\anaconda3\envs\tf_gpu1.14\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\stage_clinique\AppData\Local\Continuum\anaconda3\envs\tf_gpu1.14\lib\site-packages\keras\engine\training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "C:\Users\stage_clinique\AppData\Local\Continuum\anaconda3\envs\tf_gpu1.14\lib\site-packages\keras\engine\training_generator.py", line 40, in fit_generator
    model._make_train_function()
  File "C:\Users\stage_clinique\AppData\Local\Continuum\anaconda3\envs\tf_gpu1.14\lib\site-packages\keras\engine\training.py", line 509, in _make_train_function
    loss=self.total_loss)
  File "C:\Users\stage_clinique\AppData\Local\Continuum\anaconda3\envs\tf_gpu1.14\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\stage_clinique\AppData\Local\Continuum\anaconda3\envs\tf_gpu1.14\lib\site-packages\keras\optimizers.py", line 484, in get_updates
    lr_t = lr * (K.sqrt(1. - K.pow(self.beta_2, t)) /
  File "C:\Users\stage_clinique\AppData\Local\Continuum\anaconda3\envs\tf_gpu1.14\lib\site-packages\keras\backend\tensorflow_backend.py", line 1496, in sqrt
    x = tf.clip_by_value(x, zero, inf)
  File "C:\Users\stage_clinique\AppData\Local\Continuum\anaconda3\envs\tf_gpu1.14\lib\site-packages\tensorflow\python\util\dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "C:\Users\stage_clinique\AppData\Local\Continuum\anaconda3\envs\tf_gpu1.14\lib\site-packages\tensorflow\python\ops\clip_ops.py", line 67, in clip_by_value
    [t, clip_value_min, clip_value_max]) as name:
  File "C:\Users\stage_clinique\AppData\Local\Continuum\anaconda3\envs\tf_gpu1.14\lib\site-packages\tensorflow\python\framework\ops.py", line 6508, in __enter__
    g = _get_graph_from_inputs(self._values)
  File "C:\Users\stage_clinique\AppData\Local\Continuum\anaconda3\envs\tf_gpu1.14\lib\site-packages\tensorflow\python\framework\ops.py", line 6135, in _get_graph_from_inputs
    _assert_same_graph(original_graph_element, graph_element)
  File "C:\Users\stage_clinique\AppData\Local\Continuum\anaconda3\envs\tf_gpu1.14\lib\site-packages\tensorflow\python\framework\ops.py", line 6071, in _assert_same_graph
    (item, original_item))
ValueError: Tensor("training/Adam/Const:0", shape=(), dtype=float32) must be from the same graph as Tensor("sub:0", shape=(), dtype=float32).`

How should I use `clear_session()` ? Or is there another mean to clear GPU memory that is  working with hyperas?

Here is the code I am using : 

```
def create_model(x_train, y_train, x_test, y_test):
    clear_session()

    layer_activation = {{choice(['relu', 'sigmoid'])}}
    BN_momentum = {{choice([0.01, 0.99])}}
    k_reg = {{choice([None, kk.regularizers.l1(1e-5), kk.regularizers.l1(1e-9), kk.regularizers.l2(1e-5), kk.regularizers.l2(1e-9), kk.regularizers.l1_l2(1e-5, 1e-5), kk.regularizers.l1_l2(1e-9, 1e-9)])}}
    b_reg = {{choice([None, kk.regularizers.l1(1e-5), kk.regularizers.l1(1e-9), kk.regularizers.l2(1e-5), kk.regularizers.l2(1e-9), kk.regularizers.l1_l2(1e-5, 1e-5), kk.regularizers.l1_l2(1e-9, 1e-9)])}}
    a_reg = {{choice([None, kk.regularizers.l1(1e-5), kk.regularizers.l1(1e-9), kk.regularizers.l2(1e-5), kk.regularizers.l2(1e-9), kk.regularizers.l1_l2(1e-5, 1e-5), kk.regularizers.l1_l2(1e-9, 1e-9)])}}

    conv1_filters = {{choice([128, 256, 384])}}
    conv1_size = {{choice([3, 5, 7, 9])}}
    conv2_filters = {{choice([128, 256, 384])}}
    conv2_size = {{choice([3, 5, 7, 9])}}
    conv3_filters = {{choice([256, 512, 768])}}
    conv3_size = {{choice([3, 5, 7])}}
    conv4_filters = {{choice([256, 512, 768])}}
    conv4_size = {{choice([3, 5, 7])}}
    conv5_filters = {{choice([512, 768, 1024])}}
    conv5_size = {{choice([3, 5, 7])}}
    conv6_filters = {{choice([512, 768, 1024])}}
    conv6_size = {{choice([3, 5, 7])}}

    inputs = Input(shape=(32, 32, 1))
    conv1 = Conv2D(conv1_filters, conv1_size, padding='same',
                           activation=layer_activation, kernel_regularizer=k_reg, bias_regularizer=b_reg,
                           activity_regularizer=a_reg)(inputs)

    conv2 = Conv2D(conv2_filters, conv2_size, padding='same',
                           activation=layer_activation, kernel_regularizer=k_reg, bias_regularizer=b_reg,
                           activity_regularizer=a_reg)(BatchNormalization(momentum=BN_momentum)(conv1))
    pool1 = MaxPooling2D(pool_size=(2, 2))(BatchNormalization(momentum=BN_momentum)(conv2))

    conv3 = Conv2D(conv3_filters, conv3_size, padding='same',
                           activation=layer_activation, kernel_regularizer=k_reg, bias_regularizer=b_reg,
                           activity_regularizer=a_reg)(BatchNormalization(momentum=BN_momentum)(pool1))

    conv4 = Conv2D(conv4_filters, conv4_size, padding='same',
                           activation=layer_activation, kernel_regularizer=k_reg, bias_regularizer=b_reg,
                           activity_regularizer=a_reg)(BatchNormalization(momentum=BN_momentum)(conv3))
    pool2 = MaxPooling2D(pool_size=(2, 2))(BatchNormalization(momentum=BN_momentum)(conv4))

    conv5 = Conv2D(conv5_filters, conv5_size, padding='same',
                           activation=layer_activation, kernel_regularizer=k_reg, bias_regularizer=b_reg,
                           activity_regularizer=a_reg)(BatchNormalization(momentum=BN_momentum)(pool2))

    conv6 = Conv2D(conv6_filters, conv6_size, padding='same',
                           activation=layer_activation, kernel_regularizer=k_reg, bias_regularizer=b_reg,
                           activity_regularizer=a_reg)(BatchNormalization(momentum=BN_momentum)(conv5))

    n_dense_layer = {{choice([2, 3, 4])}}

    neurons_activation = {{choice(['relu', 'sigmoid'])}}
    dense1_neurons = {{choice([512, 1024])}}
    dense1 = Dense(dense1_neurons)(Flatten()(conv6))
    bn1 = BatchNormalization(momentum=BN_momentum)(dense1)
    act1 = Activation(neurons_activation)(bn1)
    drop1 = Dropout({{uniform(0, 1)}})(act1)

    if n_dense_layer != 2:
        dense2_neurons = {{choice([512, 1024])}}
        dense2 = Dense(dense2_neurons)(drop1)
        bn2 = BatchNormalization(momentum=BN_momentum)(dense2)
        act2 = Activation(neurons_activation)(bn2)
        drop2 = Dropout({{uniform(0, 1)}})(act2)

        if n_dense_layer == 4:
            dense3_neurons = {{choice([512, 1024])}}
            dense3 = Dense(dense3_neurons)(drop2)
            bn3 = BatchNormalization(momentum=BN_momentum)(dense3)
            act3 = Activation(neurons_activation)(bn3)
            drop3 = Dropout({{uniform(0, 1)}})(act3)
            last_dense = Dense(10, activation='softmax')(drop3)

        else:
            last_dense = Dense(10, activation='softmax')(drop2)

    else:
        last_dense = Dense(10, activation='softmax')(drop1)

    model = Model(inputs=inputs, outputs=last_dense)

    model.compile(optimizer={{choice([Adam(), Adadelta(), Nadam()])}}, loss="categorical_crossentropy",
                  metrics=['categorical_accuracy'])

    lrate_policy = {{choice(['clr', 'lrate'])}}

    if lrate_policy == 'clr':
        minLR = 1e-4
        maxLR = 1e-1
        lrate_function = CyclicLR(mode='triangular', base_lr=minLR, max_lr=maxLR, step_size=5 * 100)
    else:
        def step_decay(epoch):
            if epoch > 14:
                return 0.015 * 0.8 ** (epoch - 14 + 1)
            else:
                return 0.015
        lrate_function = kk.callbacks.LearningRateScheduler(step_decay, verbose=1)

    history = model.fit_generator(generator_batch_KFoldCV(50, x_train, y_train), epochs=5,
                                  validation_data=generator_batch_KFoldCV(25, x_test, y_test),
                                  validation_steps=80,
                                  steps_per_epoch=200,
                                  callbacks=[lrate_function], verbose=1)
    validation_acc = np.amax(history.history['val_categorical_accuracy'])
    print('Best validation acc of epoch:', validation_acc)

    return {'loss': -validation_acc, 'status': STATUS_OK, 'model': model}
```

```
def bayesian_optimization():
    time1 = time.time()
    functions = [CyclicLR, generator_batch_KFoldCV,]
    best_run, best_model = optim.minimize(model=create_model, data=data, algo=tpe.suggest,
                                          max_evals=50, trials=Trials(), rseed=111, functions=functions, keep_temp=True)

    test_set_path = 'E:\\mnist_rotation_new\\Test3'

    cheminsTrainX = [os.path.join(test_set_path, _) for _ in os.listdir(test_set_path)]

    imagesTestX = []
    labelsTestY = []

    print('== Preparing Test set ==')
    for _ in cheminsTrainX:
        if (cheminsTrainX.index(_) + 1) % 1000 == 0:
            print(str(cheminsTrainX.index(_) + 1) + '/' + str(len(cheminsTrainX)))
        imageTrX = np.pad(sitk.GetArrayFromImage(sitk.ReadImage(_)), 2, mode='constant')
        imagesTestX.append(imageTrX.reshape(imageTrX.shape[0], imageTrX.shape[1], 1))
        repY = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        repY[int(os.path.splitext(_)[0].split('Label')[-1][:-4])] = 1
        labelsTestY.append(repY)

    print("Evalutation of best performing model:")
    print(best_model.evaluate(x=np.array(imagesTestX), y=np.array(labelsTestY)))
    print("Best performing model chosen hyper-parameters:")
    print(best_run)
    print('Time: ', time.time() - time1)
```

Thanks for your answers.

Packages versions:
- Keras-gpu v2.2.4
- Hyperas v0.4.1
- Hyperopt v0.2.2
- Tensorflow v1.14.0

**Comment by TimZaragori** [comment]
It seems that it was coming from `model.compile(optimizer={{choice([Adam(), Adadelta(), Nadam()])}}, loss="categorical_crossentropy", metrics=['categorical_accuracy'])` where I shouldn't give the optimizers as functions to the search space but as strings (`{{choice(['adam', 'adadelta', 'nadam'])}}`).
Another solution is to make this choice with strings before compiling and assigning the right optimizer in an `if ... else ...` statement. I change `k_reg`, `b_reg`, `a_reg` in the same way.

Nonetheless, I still had problem since I ran OOM after a few iterations even though I am able to run the maximum model size on its own outside hyperas. `return {'loss': -validation_acc, 'status': STATUS_OK}` instead of `return {'loss': -validation_acc, 'status': STATUS_OK, 'model': model}` was the solution.
