### ISSUE TITLE
Optimizing LSTM with embedding matrix - TypeError: module, class, method, function, traceback, frame, or code object was expected, got tuple

### ISSUE THREAD

**Issue by jlperezg** [maxpumperla/hyperas#262]
First of all thank you very much for your work, 

I'm trying to use your framework to optimize hiperparameters in my LSTM network in order to implement a sentiment analysis classifier. 

I used some snippet you posted but I cannot make it work. I think the main issue is how to calculate embedding_matrix (I'm using word embedings) to train the network. I trained separately tokenize to get weights file. 

**I'm getting the following error:**

>>> Hyperas search space:

def get_space():
    return {
        'Dropout': hp.uniform('Dropout', 0, 1),
        'optimizer': hp.choice('optimizer', ['rmsprop', 'adam', 'sgd']),
    }

Traceback (most recent call last):
  File "optim_keras.py", line 132, in <module>
    best_run = optim.minimize(model=keras_model,data=get_data(),algo=tpe.suggest,max_evals=10,trials=Trials())
  File "/usr/bin/anaconda3/lib/python3.7/site-packages/hyperas/optim.py", line 69, in minimize
    keep_temp=keep_temp)
  File "/usr/bin/anaconda3/lib/python3.7/site-packages/hyperas/optim.py", line 98, in base_minimizer
    model_str = get_hyperopt_model_string(model, data, functions, notebook_name, verbose, stack)
  File "/usr/bin/anaconda3/lib/python3.7/site-packages/hyperas/optim.py", line 198, in get_hyperopt_model_string
    data_string = retrieve_data_string(data, verbose)
  File "/usr/bin/anaconda3/lib/python3.7/site-packages/hyperas/optim.py", line 219, in retrieve_data_string
    data_string = inspect.getsource(data)
  File "/usr/bin/anaconda3/lib/python3.7/inspect.py", line 973, in getsource
    lines, lnum = getsourcelines(object)
  File "/usr/bin/anaconda3/lib/python3.7/inspect.py", line 955, in getsourcelines
    lines, lnum = findsource(object)
  File "/usr/bin/anaconda3/lib/python3.7/inspect.py", line 768, in findsource
    file = getsourcefile(object)
  File "/usr/bin/anaconda3/lib/python3.7/inspect.py", line 684, in getsourcefile
    filename = getfile(object)
  File "/usr/bin/anaconda3/lib/python3.7/inspect.py", line 666, in getfile
    type(object).__name__))
TypeError: module, class, method, function, traceback, frame, or code object was expected, got tuple

Thank you in advance for your help 

Here's my code
```

from hyperopt import Trials, STATUS_OK, tpe
from hyperas import optim
from hyperas.distributions import choice, uniform



def get_data():
  import pickle
  from keras.preprocessing import sequence
  from keras.models import Sequential
  from keras.layers.core import Dense, Dropout, Activation
  from keras.layers.embeddings import Embedding
  from keras.layers.recurrent import LSTM
  from keras.datasets import imdb
  from keras.callbacks import EarlyStopping, ModelCheckpoint
  from keras.preprocessing.sequence import pad_sequences
  from keras.utils import to_categorical
  from sklearn.model_selection import train_test_split, StratifiedShuffleSplit
  import classes.filtros as NT
  import classes.data_processing as DP
  import classes.embeddings as EB
  import classes.model as M
  import classes.token as T
  import classes.parameters as Params
  import pandas as pd
  import numpy as np
  import sys
  import time 

  # Carga de datos 
  print('Loading data...')
  #instanciamos objetos necesarios
  text_array = NT.NormalizeText()
  data_processing = DP.DataProcessing()
  word_embedding = EB.ProcessEmbeddings()
  w2v = word_embedding.get_word2vec(Params.W2V_FILE)
  data_set = data_processing.load_data()

  # Separacion de los valores para tener un training set equilibrado
  neutros = [row for row in data_set if 0  == row[2]]
  positiv = [row for row in data_set if 1  == row[2]]
  negativ = [row for row in data_set if -1 == row[2]]


  df_neutros = pd.DataFrame.from_records(neutros)
  df_positiv = pd.DataFrame.from_records(positiv)
  df_negativ = pd.DataFrame.from_records(negativ)

  minimo = np.min([len(df_neutros),len(df_positiv),len(df_negativ)])
  df_final = pd.concat([df_neutros[:minimo], df_positiv[:minimo], df_negativ[:minimo]], ignore_index=True)

    # Cargamos el tokenizer aprendido
  token_path = './models/Tokenizer.pkl'
  t_m = T.TokenizerModel()
  with open(token_path, 'rb') as f:
      t_m.t = pickle.load(f)


  # # Procesado del texto y generación del token list
  filtered = pd.DataFrame(columns=['textos'])
  for row in df_final.itertuples():
    texto_filt = word_embedding.clean_text(row._2)
    filtered.loc[row.Index] = texto_filt

  encoded_docs = t_m.t.texts_to_sequences(filtered['textos'])
  
  # Codificamos los Documentos de entrada
  X = pad_sequences(encoded_docs, maxlen=Params.MAX_SEQUENCE_LENGTH, padding='post')
  y = df_final[2]
  # # Separamos en train y test 
  sss = StratifiedShuffleSplit(n_splits=15,test_size=0.15)

  for train_index, test_index in sss.split(X, y):
      X_train, X_test = X[train_index], X[test_index]
      Y_train, Y_test = y[train_index], y[test_index]

  # # Debemos cambiar a categorical las etiquetas dada la función de pérdida que usamos en el entrenamiento
  y_train_bin = to_categorical(Y_train, num_classes=3, dtype='int32')
  y_test_bin = to_categorical(Y_test, num_classes=3, dtype='int32')

  return X_train,y_train_bin,X_test,y_test_bin


def keras_model(X_train,y_train_bin,X_test,y_test_bin):
  import pickle
# Definición del modelo y entrenamiento

  word_embedding = EB.ProcessEmbeddings()
  w2v = word_embedding.get_word2vec(Params.W2V_FILE)
  text_array = NT.NormalizeText()
  # Cargamos el tokenizer aprendido
  token_path = './models/Tokenizer.pkl'
  t_m = T.TokenizerModel()
  with open(token_path, 'rb') as f:
      t_m.t = pickle.load(f)

  # Generación de la embedding matrix (vocab_size, t, w2v, text_array)
  embedding_matrix = word_embedding.Generate_Matrix(Params.MAX_NB_WORDS, t_m.t, w2v,text_array)

  print('Build model...')
  # Modelo LSTM
  model   = Sequential()
  model.add(Embedding(Params.MAX_NB_WORDS, output_dim=Params.EMBEDDING_DIM, input_length=Params.MAX_SEQUENCE_LENGTH, weights=[embedding_matrix], trainable=False))
  model.add(Bidirectional(LSTM(Params.LSTM_UNITS_1ST,  return_sequences=False)))
  model.add(Dropout({{uniform(0, 1)}}))
  model.add(Dense(3, activation='softmax'))

  model.compile(optimizer={{choice(['rmsprop', 'adam', 'sgd'])}}, loss='categorical_crossentropy', metrics=['categorical_accuracy'])
  model.train(X_train, y_train_bin, X_test, y_test_bin)



  early_stopping = EarlyStopping(monitor='val_loss', patience=4)
  checkpointer = ModelCheckpoint(filepath='keras_weights.hdf5',
                                   verbose=1,
                                   save_best_only=True)

  hist = model.fit(X_train, y_train_bin,
                     nb_epoch=1,
                     validation_split=0.08,
                     show_accuracy=True,
                     callbacks=[early_stopping, checkpointer])

  score, acc = model.evaluate(X_test, y_test_bin, show_accuracy=True, verbose=0)

  print('Test accuracy:', acc)
  return {'loss': -acc, 'status': STATUS_OK}



if __name__ == '__main__':
    best_run = optim.minimize(model=keras_model,data=get_data(),algo=tpe.suggest,max_evals=10,trials=Trials())
    print(best_run)




```

**Comment by anasouza26** [comment]
Hey! I'm having the same problem... I'm running my code on a Jupyter Notebook. Is that a problem?
Here's the error:

TypeError Traceback (most recent call last)
in
9 max_evals=5,
10 trials=Trials(),
---> 11 notebook_name='teste')
12 x_train, x_train, x_val, y_val = data()
13 print("Evalutation of best performing model:")

~\AppData\Local\Continuum\anaconda3\lib\site-packages\hyperas\optim.py in minimize(model, data, algo, max_evals, trials, functions, rseed, notebook_name, verbose, eval_space, return_space, keep_temp)
67 notebook_name=notebook_name,
68 verbose=verbose,
---> 69 keep_temp=keep_temp)
70
71 best_model = None

~\AppData\Local\Continuum\anaconda3\lib\site-packages\hyperas\optim.py in base_minimizer(model, data, functions, algo, max_evals, trials, rseed, full_model_string, notebook_name, verbose, stack, keep_temp)
96 model_str = full_model_string
97 else:
---> 98 model_str = get_hyperopt_model_string(model, data, functions, notebook_name, verbose, stack)
99 temp_file = './temp_model.py'
100 write_temp_files(model_str, temp_file)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\hyperas\optim.py in get_hyperopt_model_string(model, data, functions, notebook_name, verbose, stack)
196
197 functions_string = retrieve_function_string(functions, verbose)
--> 198 data_string = retrieve_data_string(data, verbose)
199 model = hyperopt_keras_model(model_string, parts, aug_parts, verbose)
200

~\AppData\Local\Continuum\anaconda3\lib\site-packages\hyperas\optim.py in retrieve_data_string(data, verbose)
217
218 def retrieve_data_string(data, verbose=True):
--> 219 data_string = inspect.getsource(data)
220 first_line = data_string.split("\n")[0]
221 indent_length = len(determine_indent(data_string))

~\AppData\Local\Continuum\anaconda3\lib\inspect.py in getsource(object)
971 or code object. The source code is returned as a single string. An
972 OSError is raised if the source code cannot be retrieved."""
--> 973 lines, lnum = getsourcelines(object)
974 return ''.join(lines)
975

~\AppData\Local\Continuum\anaconda3\lib\inspect.py in getsourcelines(object)
953 raised if the source code cannot be retrieved."""
954 object = unwrap(object)
--> 955 lines, lnum = findsource(object)
956
957 if istraceback(object):

~\AppData\Local\Continuum\anaconda3\lib\inspect.py in findsource(object)
766 is raised if the source code cannot be retrieved."""
767
--> 768 file = getsourcefile(object)
769 if file:
770 # Invalidate cache if needed.

~\AppData\Local\Continuum\anaconda3\lib\inspect.py in getsourcefile(object)
682 Return None if no way can be identified to get the source.
683 """
--> 684 filename = getfile(object)
685 all_bytecode_suffixes = importlib.machinery.DEBUG_BYTECODE_SUFFIXES[:]
686 all_bytecode_suffixes += importlib.machinery.OPTIMIZED_BYTECODE_SUFFIXES[:]

~\AppData\Local\Continuum\anaconda3\lib\inspect.py in getfile(object)
664 raise TypeError('module, class, method, function, traceback, frame, or '
665 'code object was expected, got {}'.format(
--> 666 type(object).name))
667
668 def getmodulename(path):

TypeError: module, class, method, function, traceback, frame, or code object was expected, got tuple

And my final code is:

from hyperopt import Trials, STATUS_OK, tpe
from hyperas import optim
from hyperas.distributions import choice, uniform

if name == 'main':
best_run, best_model = optim.minimize(model=model,
data=data(),
algo=tpe.suggest,
max_evals=5,
trials=Trials(),
notebook_name='teste')
x_train, x_train, x_val, y_val = data()
print("Evalutation of best performing model:")
print(best_model.evaluate(X_test, Y_test))
print("Best performing model chosen hyper-parameters:")
print(best_run)
