### ISSUE TITLE
indentation error in data()

### ISSUE THREAD

**Issue by croshong** [maxpumperla/hyperas#264]
Hi all 

I'm now struggling with hyperas to optimize hyperparameter in Keras.

It seems to be almost done, but another problems !!

When I run the python code which use hyperas, it seems another temporary  python script

called 'temp_model.py' was generated. error was from temp_model.py as shown below

 Unexpected error: <class 'IndentationError'>
Traceback (most recent call last):
  File "gen_chem_model_v2_beta_hyperas.py", line 154, in <module>
    best_run, best_model = optim.minimize(model=build_model,data=data,algo=tpe.suggest,max_evals=15,trials=Trials(),data_args=(sam,))
  File "/lwork01/miniconda3/lib/python3.6/site-packages/hyperas/optim.py", line 72, in minimize
    data_args=data_args)
  File "/lwork01/miniconda3/lib/python3.6/site-packages/hyperas/optim.py", line 109, in base_minimizer
    from temp_model import keras_fmin_fnct, get_space
  File "/awork10-3/jhjeon/enva_re/P35968/temp_model.py", line 143
    inp = '2qu6A_857_full_rec_env_f.txt'
 IndentationError: unexpected indent

Error text itself means simply indentation error. But I couldn't figure out why this error is generated
( 2qu6A_857_full_rec_env_f.txt is my input file) 

Attached files are my python script 

Any kind of suggestion or comment would be welcomed

Thanks

[keras_hyperas.py.txt](https://github.com/maxpumperla/hyperas/files/3947872/keras_hyperas.py.txt)

**Comment by JonnoFTW** [comment]
Can you please set `keep_temp=True` in your `optim.minimize` call and paste your temp_model.py in here (use the insert code button so it displays correctly)? 

Also, your `sam1` and `sam2` variables won't be accessible to `build_model`, you need to pass them in via `data_args` (and define them in your `if __name__ == "__main__` block.

**Comment by JonnoFTW** [comment]
There was an error in my code (I think), I'll push it to my branch which you can install from here while my pull request is awaiting merge: 

```
pip install -U git+https://github.com/JonnoFTW/hyperas.git
```


I've also fixed your code:

```python
#!/usr/bin/env python

import os
import sys
import subprocess
import shutil
import string
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
import statsmodels.api as sm
import sklearn
import pickle
from numpy.random import seed
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from tensorflow.python.keras.callbacks import TensorBoard
from keras.callbacks import EarlyStopping
from keras.models import Sequential
from keras.models import load_model
from keras import models, layers
from keras.layers import Dense, Dropout, Activation
from keras.layers.normalization import BatchNormalization
from tensorflow import keras
from time import time

from hyperas import optim
from hyperas.distributions import choice, uniform
from hyperopt import Trials, STATUS_OK, tpe


def fit_figure(sam, real, pred):
    plt.clf()
    plt.figure()
    X = real
    Y = pred
    #    X = sm.add_constant(X.to_numpy())
    X = sm.add_constant(X)
    smodel = sm.OLS(Y, X).fit()
    spredictions = smodel.predict(X)
    res = Y - spredictions
    ss_tot = np.sum((Y - Y.mean()) ** 2)
    ss_res = np.sum((Y - spredictions) ** 2)
    man_rsq = 1 - ss_res / ss_tot
    auto_rsq = sklearn.metrics.r2_score(Y, spredictions)
    if auto_rsq < 1:
        lig = sam.split('_')[1]
        rec = sam.split('_')[0]
        text = '%s Fit,R-squared=%f' % (sam, smodel.rsquared)
        text1 = '%s Fit,manually calc.R-squared=%f' % (sam, man_rsq)
        text2 = '%s Fit,sklearn R-squared=%f' % (sam, auto_rsq)
        with open('model/total_rsq.txt', 'a') as rf:
            rf.write('%s\n' % (text))
            rf.write('%s\n' % (text1))
            rf.write('%s\n' % (text2))
        print(text)
        print(text1)
        print(text2)
        plt.scatter(real, pred, label='original_data')
        plt.plot(real, spredictions, 'r-', label=text)
        plt.xlabel('True Values [rmsBB]')
        plt.ylabel('Predictions [rmsBB]')
        plt.legend()
        plt.savefig('modelx/' + sam + '_test_fit.png')
    return auto_rsq


def plot_history(history):
    hist = pd.DataFrame(history.history)
    hist['epoch'] = history.epoch

    plt.figure(figsize=(8, 12))

    plt.subplot(2, 1, 1)
    plt.xlabel('Epoch')
    plt.ylabel('Mean Abs Error')
    plt.plot(hist['epoch'], hist['mean_absolute_error'], label='Train Error')
    plt.plot(hist['epoch'], hist['val_mean_absolute_error'], label='Val Error')
    plt.legend()

    plt.subplot(2, 1, 2)
    plt.xlabel('Epoch')
    plt.ylabel('Mean Square Error [rmsBB^2]')
    plt.plot(hist['epoch'], hist['mean_squared_error'], label='Train Error')
    plt.plot(hist['epoch'], hist['val_mean_squared_error'], label='Val Error')
    plt.legend()

    plt.savefig('model/' + sam + '_qual.png')


def data(inp, num_layer, gpu_id):
    df = pd.read_csv(inp, sep='\t')
    cols = df.columns.tolist()
    feats = []
    for col in cols:
        if col == 'PDB' or col == 'total_score' or col == 'total_score_X' or col == 'interface_delta_X' or col == 'ligand_rms_with_super_X' or col == 'N.of.BB_full' or col == 'delta_racc' or col == 'Class' or col == 'Decision':
            continue
        feats.append(col)
    df1 = df[feats]
    train_df = df1.sample(frac=0.8, random_state=0)
    test_df = df1.drop(train_df.index)

    if 'rmsd' in cols:
        train_labels = train_df.pop('rmsd')
        test_labels = test_df.pop('rmsd')
    elif 'ligand_rms_no_super_X' in cols:
        train_labels = train_df.pop('ligand_rms_no_super_X')
        test_labels = test_df.pop('ligand_rms_no_super_X')
    return train_df, train_labels, test_df, test_labels


def build_model(x_train, y_train, x_test, y_test):
    os.environ['CUDA_VISIBLE_DEVICES'] = gpu_id
    model = Sequential()

    model.add(layers.Dense({{choice([64, 128, 256, 512])}}, input_dim=len(feats) - 1, activation='relu'))
    for i in range(int(num_layer)):
        model.add(layers.Dense({{choice([64, 128, 256, 512, 1024])}}, activation='relu'))
    model.add(layers.Dense(1, activation=None))
    model.compile(loss='mean_squared_error', optimizer='adam', metrics=['mean_absolute_error', 'mean_squared_error'])
    early_stopping = EarlyStopping(val_loss, patience=20)
    history = model.fit(x_train, y_train, epochs=1000, batch_size={{choice([10, 32, 64, 128])}}, validation_split=0.2, callbacks=[early_stopping])
    score = model.evaluate(x_test, y_test, verbose=0)
    return {'loss': score[1], 'status': STATUS_OK, 'model': model}


if __name__ == '__main__':
    sam = sys.argv[1]  # Sample name
    sam1 = sys.argv[2]  # No.of hidden layer
    sam2 = sys.argv[3]  # GPU dev id
    best_run, best_model = optim.minimize(model=build_model, data=data, algo=tpe.suggest, max_evals=1, trials=Trials(), data_args=(sam, sam1, sam2), keep_temp=True)
    x_train, y_train, x_test, y_test = data(sam, sam1, sam2)
    print("Evaluation of best performing model:")
    print(best_model.evaluate(x_test, y_test))
    print("Best performing model chosen hyper-parameters:")
    print(best_run)
```

Which generates the following data function in `temp_model.py` when calling with `script.py a 1 gpu:0`:

```python
>>> Data
  1: inp = 'a'
  2: num_layer = '1'
  3: gpu_id = 'gpu:0'
  4: df = pd.read_csv(inp,sep='\t')
  5: cols = df.columns.tolist()
  6: feats=[]
  7: for col in cols:
  8:     if col == 'PDB' or col == 'total_score' or col == 'total_score_X' or col == 'interface_delta_X' or col == 'ligand_rms_with_super_X' or col == 'N.of.BB_full' or col == 'delta_racc' or col == 'Class' or col =='Decision' :
  9:         continue
 10:     feats.append(col)
 11: df1 = df[feats]
 12: train_df = df1.sample(frac=0.8,random_state=0)
 13: test_df = df1.drop(train_df.index)
 14: 
 15: if 'rmsd' in cols:
 16:     train_labels =  train_df.pop('rmsd')
 17:     test_labels = test_df.pop('rmsd')
 18: elif 'ligand_rms_no_super_X' in cols:
 19:     train_labels =  train_df.pop('ligand_rms_no_super_X')
 20:     test_labels = test_df.pop('ligand_rms_no_super_X')
```

**Comment by croshong** [comment]
Thanks Jonno
 As you write in here, I reinstall hyperas using command
 pip install -U git+https://github.com/JonnoFTW/hyperas.git
 and fixed code 
 but there is still indentation error.
 Attached compress files include fixed code by you and test.txt which is input file , temp_model.py 
 generated by fixed code 
 Can there be any kind of system related problem such as tab size in vi editor?
 Can you please check once again?
 really thanks 
 regards
[error.zip](https://github.com/maxpumperla/hyperas/files/3958868/error.zip)

**Comment by JonnoFTW** [comment]
Never indent your code with tabs. Always use 4 spaces. Hyperas only works with 4 space indented code. Replace your tabs with 4 spaces (now and forever).

**Comment by croshong** [comment]
Thanks Jonno
You're right the problem was indentation. when I use 4 spaces instead of tab, there was no error and the code works well 
really thanks !!
Regards
