### ISSUE TITLE
Error when run as a module like "python -m test.test"

### ISSUE THREAD

**Issue by buptxiaofeng** [maxpumperla/hyperas#38]
Unexpected error: <type 'exceptions.SyntaxError'>
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/hyhy/dicom/opt/test.py", line 117, in <module>
    voting='hard')
  File "/usr/local/lib/python2.7/dist-packages/hyperas/optim.py", line 46, in best_ensemble
    data=data, algo=algo, max_evals=max_evals, trials=trials)
  File "/usr/local/lib/python2.7/dist-packages/hyperas/optim.py", line 51, in best_models
    base_minimizer(model, data, algo, max_evals, trials)
  File "/usr/local/lib/python2.7/dist-packages/hyperas/optim.py", line 96, in base_minimizer
    from temp_model import keras_fmin_fnct, get_space
  File "temp_model.py", line 1
    importers when locating support scripts as well as when importing modules.
                 ^
SyntaxError: invalid syntax

**Comment by maxpumperla** [comment]
Why would you want to do this?

**Comment by buptxiaofeng** [comment]
I just want to run my code as a module. It seems that hyperas would create a temp file, which is not in the right directory. In my example, python -m test.test, the first test is a dir name and the second is a module name.
