### ISSUE TITLE
np is not available to fmin()'s call

### ISSUE THREAD

**Issue by jaggzh** [maxpumperla/hyperas#75]
I'm not sure how this works, but the optim.py:87 call to fmin() is erroring with np not being available:
    return fmin(keras_fmin_fnct,
                    space=get_space(),
                    algo=algo,
                    max_evals=max_evals,
                    trials=trials,
                    rstate=np.random.RandomState(rseed))

Here's the traceback:
Traceback (most recent call last):
  File "./pagedeform.py", line 1592, in <module>
    trials=Trials())
  File "/home/jaggz/.local/lib/python2.7/site-packages/hyperas/optim.py", line 42, in minimize
    notebook_name=notebook_name, verbose=verbose)
  File "/home/jaggz/.local/lib/python2.7/site-packages/hyperas/optim.py", line 92, in base_minimizer
    rstate=np.random.RandomState(rseed))
  File "/home/jaggz/.local/lib/python2.7/site-packages/hyperopt/fmin.py", line 307, in fmin
    return_argmin=return_argmin,
  File "/home/jaggz/.local/lib/python2.7/site-packages/hyperopt/base.py", line 635, in fmin
    return_argmin=return_argmin)
  File "/home/jaggz/.local/lib/python2.7/site-packages/hyperopt/fmin.py", line 320, in fmin
    rval.exhaust()
  File "/home/jaggz/.local/lib/python2.7/site-packages/hyperopt/fmin.py", line 199, in exhaust
    self.run(self.max_evals - n_done, block_until_done=self.async)
  File "/home/jaggz/.local/lib/python2.7/site-packages/hyperopt/fmin.py", line 173, in run
    self.serial_evaluate()
  File "/home/jaggz/.local/lib/python2.7/site-packages/hyperopt/fmin.py", line 92, in serial_evaluate
    result = self.domain.evaluate(spec, ctrl)
  File "/home/jaggz/.local/lib/python2.7/site-packages/hyperopt/base.py", line 840, in evaluate
    rval = self.fn(pyll_rval)
  File "/home/jaggz/projects/pagedeform/temp_model.py", line 191, in keras_fmin_fnct
NameError: global name 'np' is not defined

**Comment by jaggzh** [comment]
More information.
When displaying the processed code, it shows that it strips down my "import numpy as np" line:
try:
    from keras.callbacks import ModelCheckpoint, LambdaCallback
except:
    pass

try:
    import numpy
except:
    pass

The original code is:
from keras.callbacks import ModelCheckpoint, LambdaCallback
import numpy as np
import sys
from os import listdir


I'm not sure why it's getting stripped.
If I include "import numpy as np" right in my model function, the import line is stripped entirely (leaving just a blank line in the hyperas output), so it still errors on the reference to np.

**Comment by maxpumperla** [comment]
@jaggzh this has now been fixed in master!
