### ISSUE TITLE
IdentationError when running optimizer

### ISSUE THREAD

**Issue by ben0it8** [maxpumperla/hyperas#78]
I get the following Traceback whenever I try to run the optimizer:
Untitled.py
Traceback (most recent call last):
  File "Untitled.py", line 165, in <module>
    trials=Trials())
  File "/Users/d069049/anaconda/lib/python2.7/site-packages/hyperas/optim.py", line 42, in minimize
    notebook_name=notebook_name, verbose=verbose)
  File "/Users/d069049/anaconda/lib/python2.7/site-packages/hyperas/optim.py", line 62, in base_minimizer
    model_str = get_hyperopt_model_string(model, data, notebook_name, verbose, stack)
  File "/Users/d069049/anaconda/lib/python2.7/site-packages/hyperas/optim.py", line 132, in get_hyperopt_model_string
    imports = extract_imports(cleaned_source, verbose)
  File "/Users/d069049/anaconda/lib/python2.7/site-packages/hyperas/utils.py", line 31, in extract_imports
    tree = ast.parse(source)
  File "/Users/d069049/anaconda/lib/python2.7/ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 57
    for lab in labels:
                     ^
IndentationError: unindent does not match any outer indentation level

I followed the way it is advised in the examples.

**Comment by desertnaut** [comment]
Get the same error, whatever I have tried! Mind you sharing your solution? Thanks
