### ISSUE TITLE
TypeError: ap_uniform_sampler() takes at least 4 arguments (5 given)

### ISSUE THREAD

**Issue by ben0it8** [maxpumperla/hyperas#79]
hello, I have the above error when calling optim.minimize() with the exact same arguments as in the examples.

full traceback:

Traceback (most recent call last):
  File "Untitled.py", line 162, in <module>
    trials=Trials())
  File "/Users/d069049/anaconda/lib/python2.7/site-packages/hyperas/optim.py", line 42, in minimize
    notebook_name=notebook_name, verbose=verbose)
  File "/Users/d069049/anaconda/lib/python2.7/site-packages/hyperas/optim.py", line 92, in base_minimizer
    rstate=np.random.RandomState(rseed))
  File "/Users/d069049/anaconda/lib/python2.7/site-packages/hyperopt/fmin.py", line 307, in fmin
    return_argmin=return_argmin,
  File "/Users/d069049/anaconda/lib/python2.7/site-packages/hyperopt/base.py", line 635, in fmin
    return_argmin=return_argmin)
  File "/Users/d069049/anaconda/lib/python2.7/site-packages/hyperopt/fmin.py", line 320, in fmin
    rval.exhaust()
  File "/Users/d069049/anaconda/lib/python2.7/site-packages/hyperopt/fmin.py", line 199, in exhaust
    self.run(self.max_evals - n_done, block_until_done=self.async)
  File "/Users/d069049/anaconda/lib/python2.7/site-packages/hyperopt/fmin.py", line 157, in run
    self.rstate.randint(2 ** 31 - 1))
  File "/Users/d069049/anaconda/lib/python2.7/site-packages/hyperopt/tpe.py", line 812, in suggest
    = tpe_transform(domain, prior_weight, gamma)
  File "/Users/d069049/anaconda/lib/python2.7/site-packages/hyperopt/tpe.py", line 793, in tpe_transform
    s_prior_weight
  File "/Users/d069049/anaconda/lib/python2.7/site-packages/hyperopt/tpe.py", line 684, in build_posterior
    b_post = fn(*b_args, **dict(named_args))
TypeError: ap_uniform_sampler() takes at least 4 arguments (5 given)

Thanks in advance!

**Comment by maxpumperla** [comment]
It's very hard for me to tell what exactly you're doing, but I suspect an old version of hyperopt. Would you mind upgrading? We've done quite a few changes to hyperopt over time.
