### ISSUE TITLE
NameError : name XXX(function name) is not defined

### ISSUE THREAD

**Issue by FreeAJust** [maxpumperla/hyperas#87]
When I use a function in data() function, it raises this wrong.

just like this:
def read_train_data():
   ....

def data():
   train_data = read_train_data()
   ...

The error message are below:
Unexpected error: <type 'exceptions.NameError'>
Traceback (most recent call last):
  File "31_hyper_tune.py", line 295, in <module>
    trials=Trials())
  File "/home/yinqijin/anaconda2/lib/python2.7/site-packages/hyperas-0.3-py2.7.egg/hyperas/optim.py", line 43, in minimize
    notebook_name=notebook_name, verbose=verbose)
  File "/home/yinqijin/anaconda2/lib/python2.7/site-packages/hyperas-0.3-py2.7.egg/hyperas/optim.py", line 68, in base_minimizer
    from temp_model import keras_fmin_fnct, get_space
  File "/home/yinqijin/WorkSpace/2.RNA_Structure_Profile/temp_model.py", line 135, in <module>
    DData_train_ehr,DData_train_pro,DData_train_label = read_train_data(DData_train_dir)
NameError: name 'read_train_data' is not defined

What's wrong ?

Thanks

**Comment by maxpumperla** [comment]
https://github.com/maxpumperla/hyperas/blob/master/examples/use_intermediate_functions.py

This has lately been addressed. You can now specify intermediate functions, as shown above.
