### ISSUE TITLE
Complete example in readme: TypeError 'module' object is not callable

### ISSUE THREAD

**Issue by caugusta** [maxpumperla/hyperas#89]
I'm trying to run the complete example from the main page (the readme, [here](https://github.com/maxpumperla/hyperas)), and I'm getting an error:

```
Traceback (most recent call last):
  File "hyperas_2.py", line 74, in <module>
    trials=t1)
  File "/user/pkgs/anaconda2/lib/python2.7/site-packages/hyperas/optim.py", line 32, in minimize
    best_run = base_minimizer(model, data, algo, max_evals, trials, rseed)
  File "/user/pkgs/anaconda2/lib/python2.7/site-packages/hyperas/optim.py", line 120, in base_minimizer
    rstate=np.random.RandomState(rseed))
  File "/user/pkgs/anaconda2/lib/python2.7/site-packages/hyperopt-0.0.4-py2.7.egg/hyperopt/fmin.py", line 306, in fmin
  File "/user/pkgs/anaconda2/lib/python2.7/site-packages/hyperopt-0.0.4-py2.7.egg/hyperopt/base.py", line 633, in fmin
TypeError: 'module' object is not callable
```

I wonder if hyperopt is not playing nicely with fmin? There doesn't seem to be a problem with Trials() on its own, because I can call `t1 = Trials()` in `__main__` no problem.

**Comment by maxpumperla** [comment]
not sure what's wrong on your machine, but the example definitely works. note that you have an insanely old hyperopt version, for instance. please try upgrading *everything* :)
